NAME=Dynamic / Matugen
MODE=dark

ACCENT=#ffb4a7
SELECTION=#5d3f3a
MUTED=#d8c2be

BACKGROUND=#1a1110
DARK_BACKGROUND=#1a1110
DARKER_BACKGROUND=#140c0b
LIGHTER_BACKGROUND=#322826

FOREGROUND=#f1dfdb
DARK_FOREGROUND=#a08c89
LIGHT_FOREGROUND=#d8c2be
BRIGHT_FOREGROUND=#f1dfdb

RED=#ffb4ab
YELLOW=#e8b079
ORANGE=#ddc48c
GREEN=#b9c67b
CYAN=#e7bdb6
BLUE=#ffb4a7
MAGENTA=#ddc48c
BROWN=#ad7765

BRIGHT_RED=#fcbbb3
BRIGHT_YELLOW=#e9b88a
BRIGHT_GREEN=#c3ca8c
BRIGHT_CYAN=#e8c3bc
BRIGHT_BLUE=#fcbbb0
BRIGHT_MAGENTA=#e0c89a

SURFACE=#271d1c
ICON_THEME=auto
