NAME=Kanagawa Wave
MODE=dark

ACCENT=#c34043
SELECTION=#2d4f67
MUTED=#727169

BACKGROUND=#1f1f28
DARK_BACKGROUND=#16161d
DARKER_BACKGROUND=#090618
LIGHTER_BACKGROUND=#2a2a37

FOREGROUND=#dcd7ba
DARK_FOREGROUND=#727169
LIGHT_FOREGROUND=#c8c093
BRIGHT_FOREGROUND=#e6e1cf

RED=#c34043
YELLOW=#c0a36e
ORANGE=#ffa066
GREEN=#76946a
CYAN=#6a9589
BLUE=#7e9cd8
MAGENTA=#957fb8
BROWN=#c8c093

BRIGHT_RED=#e46876
BRIGHT_YELLOW=#e6c384
BRIGHT_GREEN=#98bb6c
BRIGHT_CYAN=#7fb4ca
BRIGHT_BLUE=#7e9cd8
BRIGHT_MAGENTA=#938aa9

SURFACE=#2a2a37
ICON_THEME=Yaru-red-dark
