NAME=Gruvbox Material
MODE=dark

ACCENT=#d8a657
SELECTION=#3c3836
MUTED=#928374

BACKGROUND=#1d2021
DARK_BACKGROUND=#17191a
DARKER_BACKGROUND=#141617
LIGHTER_BACKGROUND=#282828

FOREGROUND=#ddc7a1
DARK_FOREGROUND=#7c6f64
LIGHT_FOREGROUND=#d4be98
BRIGHT_FOREGROUND=#ebdbb2

RED=#ea6962
YELLOW=#d8a657
ORANGE=#e78a4e
GREEN=#a9b665
CYAN=#89b482
BLUE=#7daea3
MAGENTA=#d3869b
BROWN=#a89984

BRIGHT_RED=#fb4934
BRIGHT_YELLOW=#fabd2f
BRIGHT_GREEN=#b8bb26
BRIGHT_CYAN=#8ec07c
BRIGHT_BLUE=#83a598
BRIGHT_MAGENTA=#d3869b

SURFACE=#282828
ICON_THEME=Yaru-yellow-dark
