NAME=Catppuccin Mocha
MODE=dark

ACCENT=#cba6f7
SELECTION=#45475a
MUTED=#9399b2

BACKGROUND=#1e1e2e
DARK_BACKGROUND=#181825
DARKER_BACKGROUND=#11111b
LIGHTER_BACKGROUND=#313244

FOREGROUND=#cdd6f4
DARK_FOREGROUND=#6c7086
LIGHT_FOREGROUND=#bac2de
BRIGHT_FOREGROUND=#f5e0dc

RED=#f38ba8
YELLOW=#f9e2af
ORANGE=#fab387
GREEN=#a6e3a1
CYAN=#94e2d5
BLUE=#89b4fa
MAGENTA=#cba6f7
BROWN=#f2cdcd

BRIGHT_RED=#eba0ac
BRIGHT_YELLOW=#f9e2af
BRIGHT_GREEN=#a6e3a1
BRIGHT_CYAN=#89dceb
BRIGHT_BLUE=#74c7ec
BRIGHT_MAGENTA=#f5c2e7

SURFACE=#313244
ICON_THEME=Yaru-purple-dark
