NAME=Sakura Blossom
MODE=dark

ACCENT=#f2a7c6
SELECTION=#402a3c
MUTED=#b994a6

BACKGROUND=#17111a
DARK_BACKGROUND=#100b12
DARKER_BACKGROUND=#0a070c
LIGHTER_BACKGROUND=#241824

FOREGROUND=#f6dce8
DARK_FOREGROUND=#806676
LIGHT_FOREGROUND=#ddbecd
BRIGHT_FOREGROUND=#fff1f7

RED=#ed7d9b
YELLOW=#e7c179
ORANGE=#e89a7e
GREEN=#9ac49f
CYAN=#8fc8c1
BLUE=#93afe0
MAGENTA=#d69adf
BROWN=#a87568

BRIGHT_RED=#ff9ab3
BRIGHT_YELLOW=#f8d690
BRIGHT_GREEN=#b1ddb6
BRIGHT_CYAN=#a8e1da
BRIGHT_BLUE=#abc7fa
BRIGHT_MAGENTA=#edb2f5

SURFACE=#241824
ICON_THEME=Yaru-magenta-dark
