NAME=Rose Pine
MODE=dark

ACCENT=#ebbcba
SELECTION=#403d52
MUTED=#908caa

BACKGROUND=#191724
DARK_BACKGROUND=#13111b
DARKER_BACKGROUND=#0f0d16
LIGHTER_BACKGROUND=#26233a

FOREGROUND=#e0def4
DARK_FOREGROUND=#6e6a86
LIGHT_FOREGROUND=#c4c1d7
BRIGHT_FOREGROUND=#f5f2ff

RED=#eb6f92
YELLOW=#f6c177
ORANGE=#ea9a97
GREEN=#9ccfd8
CYAN=#9ccfd8
BLUE=#31748f
MAGENTA=#c4a7e7
BROWN=#ebbcba

BRIGHT_RED=#ff8eaa
BRIGHT_YELLOW=#ffd89b
BRIGHT_GREEN=#b4e5ec
BRIGHT_CYAN=#b4e5ec
BRIGHT_BLUE=#5b9ab3
BRIGHT_MAGENTA=#dcc0ff

SURFACE=#1f1d2e
ICON_THEME=Yaru-magenta-dark
