NAME=Monochrome
MODE=dark

ACCENT=#ffffff
SELECTION=#343434
MUTED=#c6c6c6

BACKGROUND=#131313
DARK_BACKGROUND=#0d0d0d
DARKER_BACKGROUND=#080808
LIGHTER_BACKGROUND=#1f1f1f

FOREGROUND=#e2e2e2
DARK_FOREGROUND=#696969
LIGHT_FOREGROUND=#c6c6c6
BRIGHT_FOREGROUND=#ffffff

RED=#b5b5b5
YELLOW=#cecece
ORANGE=#c2c2c2
GREEN=#aaaaaa
CYAN=#bdbdbd
BLUE=#a0a0a0
MAGENTA=#c8c8c8
BROWN=#858585

BRIGHT_RED=#d0d0d0
BRIGHT_YELLOW=#eeeeee
BRIGHT_GREEN=#c5c5c5
BRIGHT_CYAN=#dddddd
BRIGHT_BLUE=#c0c0c0
BRIGHT_MAGENTA=#e5e5e5

SURFACE=#1f1f1f
ICON_THEME=auto
