NAME=Japanese Ink
MODE=dark

ACCENT=#b7372f
SELECTION=#302520
MUTED=#958b7a

BACKGROUND=#11130f
DARK_BACKGROUND=#0b0d0a
DARKER_BACKGROUND=#070806
LIGHTER_BACKGROUND=#191b16

FOREGROUND=#e8ddc7
DARK_FOREGROUND=#6f685c
LIGHT_FOREGROUND=#cfc3ad
BRIGHT_FOREGROUND=#fff4dc

RED=#b7372f
YELLOW=#c6a15b
ORANGE=#c9693f
GREEN=#788c5d
CYAN=#6f9690
BLUE=#7189a6
MAGENTA=#9a7185
BROWN=#8b5e4a

BRIGHT_RED=#df5549
BRIGHT_YELLOW=#e3bd70
BRIGHT_GREEN=#98ad73
BRIGHT_CYAN=#8db8b1
BRIGHT_BLUE=#91a9c7
BRIGHT_MAGENTA=#bd8da5

SURFACE=#191b16
ICON_THEME=Yaru-red-dark
